[project]
name = "Personal Portfolio Website"
ref = "HE2150"
type = "Application"
platforms = ["web"]
description = ""
license = "MIT"
repository = "https://github.com/harshjayprakash/harshjayprakash.github.io"

[version]
epoch = 4
major = 6
minor = 0
patch = 0
full = "4006.0.0"