[project]
name = "Personal Portfolio Website"
ref = "HE2150"
version = "4006.2.0"
type = "Application"
platforms = ["web"]
description = ""
license = "MIT"
repository = "https://github.com/harshjayprakash/harshjayprakash.github.io"